[package]
name = "pomosh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
colored = "2.1.0"
rodio = "0.13"

[package.metadata.cargo-machete]
ignore = ["rand"]